### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by michaeltansy** [allantatter/laravel-react#3]
Hi, been facing this issue from yesterday and havent found the solution. so here's the error I got after typing npm install

module.js:339
    throw err;
    ^

Error: Cannot find module 'depd'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\xampp\htdocs\laravelOktober\node_modules\express\lib\express.js:5:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by allantatter** [comment]
Not sure what's wrong. Just did a clean install on OS X, no problems. Still experiencing the issue?

**Comment by michaeltansy** [comment]
well unfortunately i'm using Windows 10 and some people had been solved by that kind of way but that's not solving mine. Which node_modules should I delete? node_modules in nodejs folder or node_modules inside npm folder?

**Comment by allantatter** [comment]
In your project root there is `node_modules` with other directories (`app`, `config`, `database`, `vendor`, `resources`). That `node_modules` should be deleted.

That helps, if smth went wrong during `npm install` because then you can do fresh `npm install` again.

**Comment by michaeltansy** [comment]
okay then i was wrongly delete the folder. it works now. thanks allantatter :)

**Comment by allantatter** [comment]
No problem, glad I could help :) The problem wasn't because of this package then. From time to time, smth can go wrong with `npm install`.

**Comment by michaeltansy** [comment]
ok buddy :D well finally i can try react in laravel

**Comment by michaeltansy** [comment]
allan, how do I use react function in view and controller? been trying the whole night but couldnt find the solution on how to use it.

**Comment by allantatter** [comment]
If you followed the readme about copying exaple `resources` from the package's directory (https://github.com/allantatter/laravel-react#setup-server-rendering-with-nodejs-application) then you should be able to put the following inside `routes.php` and should work when you visit the homepage.

```
<?php

Route::get('/', function () {
    return React::component('Name', ['name' => 'Allan']);
});
```

If it works, then you can also have it in the controller and return it the same way as in `routes.php` and in a blade view like `{!! React::component('Name', ['name' => 'Allan']) !!}`.

Was this the answer to your question?

**Comment by michaeltansy** [comment]
yeah that answers my question. i did copy to the resources folder and copy this following code 

"scripts": {
    "start": "cd resources/scripts && nodemon --harmony server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "dotenv": "^1.1.0",
    "envify": "^3.4.0",
    "express": "^3.5.1",
    "node-jsx": "^0.12.4",
    "react": "^0.13.1",
    "react-router": "^0.13.2"
  }
to my package.json and put them right after devDependencies. is that correct?

**Comment by michaeltansy** [comment]
okay it works now. maybe i was wrongly put the resources folder.

**Comment by allantatter** [comment]
Ok, great :)

My package.json looks like this:

```
{
  "private": true,
  "scripts": {
    "start": "cd resources/scripts && nodemon --harmony server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "laravel-elixir": "^3.0.0",
    "bootstrap-sass": "^3.0.0",
    "dotenv": "^1.1.0",
    "envify": "^3.4.0",
    "express": "^3.5.1",
    "node-jsx": "^0.12.4",
    "react": "^0.13.1",
    "react-router": "^0.13.2"
  }
}
```
